"""Reviewed supplementary lessons used to render the static course pages."""

QUESTIONS = {
1: [
('osi-and-internet', 'How do the seven OSI layers map to the Internet model?', 'OSI names physical, data link, network, transport, session, presentation, and application layers, from bottom to top. This course uses five layers: physical, link, network, transport, and application. Session and presentation responsibilities are usually handled by applications and libraries. A reference model describes responsibilities; it does not force every real protocol into exactly one box.'),
('layer-responsibilities', 'Which layer handles addressing, reliability, and flow control?', 'Link protocols deliver frames locally; IP addresses and routes datagrams across networks; transport protocols identify application endpoints with ports. Reliability and flow control can exist at more than one layer. TCP provides end-to-end reliability and receiver flow control, while some link protocols provide local recovery or flow control. IP itself does not provide reliable delivery. See the scope comparison in <a href="chapter3.html#flow-control-layers">Chapter 3</a>.'),
('network-devices', 'What is the difference between a hub, switch, router, and access point?', 'A hub repeats physical signals. A layer-2 switch forwards frames within a bridged network using MAC addresses. A router forwards IP packets between networks. An access point usually bridges wireless stations to a LAN. A home “router” often combines routing, an Ethernet switch, Wi-Fi, DHCP, NAT, and a firewall in one box; the product name does not identify just one layer.'),
('rate-and-goodput', 'Are bandwidth, throughput, goodput, and latency interchangeable?', 'No. Link rate is a capacity in bits per second; throughput is the achieved transfer rate at a specified measurement layer; application goodput counts useful payload, excluding headers and retransmissions. Latency is elapsed delivery time. A high-capacity link can still have high latency. Also distinguish bandwidth in hertz, a physical frequency range, from the informal networking use of bandwidth for data capacity.'),
('units', 'What is the difference between Mb/s, MB/s, MB, and MiB?', 'Lowercase b means bits; uppercase B means bytes. One byte is eight bits. Decimal prefixes give 1 MB = 1,000,000 bytes and 1 Mb/s = 1,000,000 bits per second. Binary prefixes give 1 MiB = 1,048,576 bytes. A 100 Mb/s link has an ideal ceiling of 12.5 MB/s before overhead. Always convert bytes to bits before using a bit-rate formula.'),
('duplex', 'What are simplex, half-duplex, and full-duplex communication?', 'Simplex sends in one direction. Half-duplex permits both directions but not simultaneous use of the shared channel. Full-duplex permits simultaneous sending and receiving. Modern switched Ethernet normally uses full-duplex point-to-point links; a conventional Wi-Fi radio shares airtime. Full-duplex does not double the stated rate in one direction: 1 Gb/s full-duplex means up to 1 Gb/s in each direction.'),
('bdp', 'Why does bandwidth–delay product matter?', 'Rate multiplied by round-trip time estimates how much data must be in flight to keep a path busy. At 100 Mb/s and 40 ms RTT, that is 4,000,000 bits, or 500,000 bytes. If a flow can keep only 64,000 bytes outstanding, its ideal window-limited rate is about 12.8 Mb/s. This estimate ignores loss, competing traffic, overhead, and receiver or application limits.'),
('checksum-proof', 'Does a valid checksum prove that data is correct?', 'No. Error-detection codes have undetectable error patterns, and an attacker can often recompute an ordinary checksum. A link CRC checks a frame over one hop; a transport checksum checks a different scope. Neither proves that the application received the intended file. Use authenticated integrity for adversarial changes, and application-level validation when correctness depends on the meaning or completeness of the data.')
],
2: [
('ports-and-sockets', 'Is a port a physical connector or a unique process identifier?', 'A transport port is a 16-bit logical number, not a cable connector. TCP and UDP have separate port namespaces. Ports 0–1023 are System Ports, 1024–49151 are User Ports, and 49152–65535 are Dynamic/Private Ports; operating systems may choose different ephemeral allocation ranges. A port alone does not globally identify a process: addresses, protocol, connection state, and socket-binding rules also matter.'),
('shared-server-port', 'How can thousands of clients use the same server port?', 'For ordinary TCP connections, the source IP, source port, destination IP, and destination port distinguish connections. A listening socket accepts connections on the service port; accepted sockets retain that local port but have different peer tuples. A client normally uses an ephemeral source port. A service on port 443 is not limited to one client or one socket.'),
('dns-not-url', 'Does DNS resolve an entire URL, and does one name mean one server?', 'DNS looks up names and record types, not a URL path such as /courses or a fragment such as #review. One name may return multiple addresses, and many names may share an address. DNS caching and load balancing can change the selected endpoint. After DNS, the application still chooses its protocol, connects, and identifies the requested resource.'),
('dns-errors', 'Are NXDOMAIN, an empty DNS answer, and SERVFAIL the same?', 'No. NXDOMAIN says the queried domain name does not exist. A NOERROR response with no matching answer can mean the name exists but has no record of the requested type, often called NODATA. SERVFAIL means resolution failed, for example because of an upstream failure or failed DNSSEC validation. Diagnose the returned status and authority information before concluding that a website is down.'),
('http-stateless', 'How can HTTP be stateless when websites remember me?', 'Stateless protocol semantics do not prohibit application state. Cookies, session identifiers, tokens, and server-side records can associate requests with a user. A cookie may hold an identifier or other data; it need not always point to a server-side session. Persistent TCP connections and HTTP authentication are separate concerns. Browser local storage is also different from cookies automatically attached to matching requests.'),
('http-status', 'Which HTTP status codes should I recognize?', '200 indicates success; 201 indicates creation; 204 has no response content. A 301 or 308 is a permanent redirect, while 302 or 307 is temporary; 307/308 preserve the method. A 304 answers conditional validation without resending the representation. 400 is a bad request, 401 requires authentication, 403 refuses access, 404 means not found, 429 limits request rate, and 5xx codes indicate server-side failure.'),
('safe-idempotent', 'Does idempotent mean safe, or that every response is identical?', 'No. Safe methods are intended to read without requesting a state change. Idempotent methods have the same intended effect when repeated as when performed once. DELETE can be idempotent while changing state; its later response may differ. A timed-out payment request may already have succeeded. Retrying a non-idempotent operation needs an application mechanism such as an idempotency key.'),
('dns-dhcp-arp', 'How do DHCP, DNS, and ARP differ?', 'DHCP supplies network configuration, DNS maps names to records, and ARP finds the local link-layer address for an IPv4 next hop. They answer different questions: “What configuration may I use?”, “What records describe this name?”, and “Which local MAC should receive this frame?” IPv6 uses Neighbor Discovery rather than ARP. A DNS failure does not necessarily mean that the host lacks an IP address.'),
('tcp-message-boundaries', 'Does one send() correspond to one recv()?', 'No. TCP is a byte stream: a read may contain part of a write or bytes from several writes. Define application framing and handle partial reads. A successful send reports local acceptance, not proof that the peer application processed the request. UDP preserves datagram boundaries, but datagrams can be lost, duplicated, reordered, or truncated by an undersized receive buffer.'),
('default-ports', 'Are the familiar port numbers mandatory?', 'They are conventions or protocol defaults, not proof of what is running. HTTP commonly uses TCP 80; HTTPS commonly uses TCP 443 or UDP 443 for HTTP/3; DNS uses UDP and TCP 53; SSH uses TCP 22; SMTP relay uses TCP 25. Configuration, proxies, and tunnels can change the observed port. Port numbers alone do not establish service identity or security.')
],
3: [
('flow-control-layers', 'In which layer do we perform flow control?', '<strong>Both the transport layer and some data-link protocols can provide flow control, with different scopes.</strong> TCP limits an end-to-end sender using the receiver’s advertised window; QUIC has stream and connection limits. Ethernet PAUSE is an optional link-level mechanism between neighboring interfaces. Applications can also apply backpressure to their own queues. “Flow control is only at layer 2” and “only at layer 4” are both incomplete answers.'),
('flow-versus-congestion', 'How is flow control different from congestion control and error control?', 'Flow control prevents a sender from overwhelming a receiver. Congestion control adapts traffic to network capacity. Error control detects damage and may recover from loss, duplication, or reordering. In TCP, rwnd is a receiver limit and cwnd is a sender’s congestion limit. A clean network can still have a slow receiver, and a fast receiver does not imply that the network has spare capacity.'),
('window-arithmetic', 'How much new TCP data can I send when bytes are already in flight?', 'In the simplified teaching model, additional allowance is max(0, min(cwnd, rwnd) − bytes in flight). If cwnd is 64 KiB, rwnd is 12 KiB, and 8 KiB is outstanding, the allowance is 4 KiB. Real implementations also track sequence-space window edges, recovery state, pacing, and application availability. The advertised window is not a promise of application processing speed.'),
('tcp-ack-meaning', 'Does a TCP ACK prove that the receiving application processed my data?', 'No. It reports transport receipt of bytes, not a successful database commit, file save, or payment. An application acknowledgment has a different meaning. After a disconnect, the sender may be unsure whether an operation finished. Exactly-once effects require application design, such as transaction identifiers and duplicate detection; TCP reliability alone cannot supply that guarantee.'),
('sequence-and-ack', 'Does TCP number packets, bytes, or messages?', 'TCP sequence numbers describe byte positions modulo 2³². A segment beginning at sequence 1000 and carrying 500 bytes covers positions 1000–1499; the cumulative ACK is 1500 if all earlier bytes arrived. SYN and FIN each consume one sequence number. An ACK without data, SYN, or FIN consumes no sequence number. Application message boundaries are not encoded by TCP.'),
('zero-window', 'What happens when the receiver advertises a zero window?', 'The sender stops sending ordinary new data beyond the receive window. Zero-window probing lets it discover that space is available even if a window update was lost. A zero window is receiver backpressure, not automatically packet loss or network congestion. The receiving application must drain buffered data before the advertised capacity can recover.'),
('mtu-mss', 'How are MTU and TCP MSS different?', 'MTU is a link’s maximum network-layer packet size; MSS is a TCP payload-size limit. With a 1500-byte IP MTU and no IP or TCP options, the usual calculation is 1460 bytes for IPv4 or 1440 for IPv6. Options and tunnels reduce the effective payload budget. Each endpoint advertises an MSS; the sender must also respect path MTU. MSS does not include the TCP header. <a href="chapter4.html#mtu-header-budget">See why Ethernet uses 1500 bytes, the 1460-byte calculation, and the complete header breakdown.</a>'),
('udp-speed', 'Is UDP always faster, and can it be reliable?', 'UDP avoids a transport handshake and supplies a small header, but performance depends on the workload and path. An application may implement acknowledgments, recovery, ordering, pacing, and congestion control above UDP, as QUIC does. That does not make UDP itself reliable. Real-time media may prefer late packets to be discarded, whereas a file-transfer protocol must recover missing content.'),
('close-and-timewait', 'Why can TCP close take four messages, and what is TIME_WAIT?', 'Each direction of a TCP byte stream closes independently, so FIN and ACK exchanges may use four segments; an ACK and FIN can also be combined. TIME_WAIT retains state long enough to handle delayed duplicates and retransmit the final ACK if needed. It normally occurs at the actively closing side. A reset aborts a connection and has different semantics from an orderly FIN close.'),
('sequence-space', 'Why do Go-Back-N and Selective Repeat need different sequence spaces?', 'With m sequence bits, the textbook Go-Back-N sender window is at most 2^m − 1. With equal Selective Repeat windows, each is at most 2^(m−1). Selective Repeat accepts out-of-order packets and needs separation between old and new windows. These bounds assume bounded packet lifetime; they do not solve arbitrary delay across repeated sequence-number reuse. State whether an ACK names the last accepted or next expected packet.')
],
4: [
('router-ip-count', 'How many IP addresses does a router have?', '<strong>There is no fixed number.</strong> In a basic IPv4 exercise, count one address per configured routed interface: three interfaces on three subnets usually mean three addresses. Real routers may have multiple addresses on an interface, IPv4 and IPv6 together, loopbacks, VLAN subinterfaces, tunnel interfaces, or unnumbered links. Count the configured logical interfaces and address families, not simply the physical sockets. <a href="https://www.rfc-editor.org/rfc/rfc4291.html#section-2.1">IPv6 addressing model</a>.'),
('router-address-example', 'Can you show a concrete router-address example?', 'Suppose R has LAN-A 192.168.10.1/24, LAN-B 192.168.20.1/24, WAN 203.0.113.2/30, and loopback 192.0.2.1/32. That is four configured IPv4 addresses on four logical interfaces. Adding an IPv6 link-local and global address to a LAN interface increases the count without adding a cable. The WAN and loopback prefixes here are documentation examples, not addresses to use on the public Internet.'),
('router-ports', 'Does every physical router port need its own IP address?', 'No. A routed port may carry addresses directly. A layer-2 switch port inside the same device may belong to a VLAN whose routed interface carries the IP address. One physical trunk can support multiple routed VLAN subinterfaces. Loopbacks have no physical cable. Some point-to-point interfaces use unnumbered addressing. Physical port count is therefore not a general IP-address formula.'),
('gateway-ip', 'Is the default gateway the destination IP of every outgoing packet?', 'Usually not. For a remote server, the packet retains the server’s destination IP. On an Ethernet LAN, the enclosing frame uses the next-hop gateway’s MAC address. The gateway removes that frame and forwards the IP packet. The gateway IP is used to resolve and reach the next hop; it does not replace the remote destination IP. NAT and tunnels add separate transformations.'),
('host-routing', 'How does a host decide whether to use a gateway?', 'A host consults its routing table and normally chooses the longest matching prefix. A connected route makes a destination on-link; another specific route may use a chosen gateway; a default route is the fallback. If no route matches, forwarding fails. “Same subnet, otherwise default gateway” is a useful beginner example, but it omits more-specific routes, multiple interfaces, and policy routing.'),
('subnet-exceptions', 'Does every IPv4 subnet have 2^h − 2 usable host addresses?', 'That is the usual rule for conventional broadcast subnets with at least two host bits, not a universal formula. A /31 point-to-point link can use both addresses under RFC 3021. A /32 denotes one IPv4 address, often a host route or loopback. IPv6 has no broadcast address, so do not subtract a broadcast address from its subnet size. <a href="https://www.rfc-editor.org/rfc/rfc3021.html">RFC 3021</a>.'),
('private-public', 'Are private, public, static, and dynamic addresses the same distinction?', 'No. Private/public describes address scope and allocation; static/dynamic describes configuration. RFC 1918 IPv4 ranges are 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16. A private address may be static or leased by DHCP, and so may a public address. A public address is not necessarily reachable: routes, firewalls, and service bindings still matter. 100.64.0.0/10 is shared address space, not RFC 1918 space.'),
('special-addresses', 'What do 127.0.0.1, 0.0.0.0, 169.254/16, ::1, and fe80:: mean?', '127.0.0.0/8 is IPv4 loopback, commonly used as 127.0.0.1. The unspecified 0.0.0.0 address is context-dependent; binding a server to it commonly means all local IPv4 interfaces. The route 0.0.0.0/0 means default, a different use. 169.254.0.0/16 is IPv4 link-local. IPv6 uses ::1 for loopback, :: for unspecified, and fe80::/10 for link-local addresses; link-local communication stays on the link.'),
('nat-pat', 'Is every NAT a port translator or a firewall?', 'No. Basic address translation and address-plus-port translation are different forms; home gateways commonly use the latter, also called NAPT or PAT. NAT does not inherently encrypt or authenticate traffic. A firewall enforces a traffic policy. Both functions may share the same device, and unsolicited inbound traffic may fail without a mapping, but translation is not a complete security policy.'),
('fragmentation-details', 'Who fragments and reassembles IP packets?', 'An IPv4 source or router may fragment when permitted; DF forbids router fragmentation. Reassembly occurs at the destination. IPv6 routers never fragment forwarded packets; an IPv6 source can use a Fragment extension header. Fragment offsets use 8-byte units. Losing one required fragment prevents reconstruction of the original packet, so applications should avoid relying on fragmentation and respect path MTU.'),
('dhcp-slaac', 'How does a new device obtain an address before it can communicate?', 'IPv4 DHCP can begin with source 0.0.0.0 and broadcast discovery; the initial exchange is commonly Discover, Offer, Request, ACK. Relays connect clients to servers on other subnets. Existing leases may renew differently. IPv6 can use Router Advertisements and SLAAC, DHCPv6, or both. IPv6 default-router discovery uses Router Advertisements; DHCPv6 does not replace it.'),
('ttl-hops', 'Is TTL a time measurement, and does every switch decrement it?', 'In ordinary IPv4 forwarding, each router reduces TTL by at least one; IPv6 calls the field Hop Limit. Layer-2 switches do not decrement the IP field merely while bridging a frame. An initial value of 64 allows at most 63 successful router forwards before the next router expires the packet. This limits loops; it does not measure elapsed wall-clock time.')
],
5: [
('route-selection-order', 'Does a lower route metric beat a longer prefix?', 'Not during ordinary destination lookup. Once routes are installed, a matching /24 is more specific than a matching /16, even if their metrics differ. Selecting the preferred candidate for the same prefix is a separate control-plane decision using protocol preference, metric, and policy. Administrative-distance values are vendor-specific. Do not mix FIB longest-prefix matching with RIB route selection.'),
('routing-tables', 'What is the difference between RIB, FIB, ARP table, and MAC table?', 'The RIB holds routing candidates and selected routes. The FIB supports packet forwarding. An ARP or Neighbor Discovery cache resolves a local next-hop IP address to link-layer information. A switch MAC table maps a MAC address and VLAN to a port. These structures cooperate but cannot substitute for one another: a route may exist even when neighbor resolution fails.'),
('routing-protocol-layer', 'Which layers do routing protocols use?', 'Routing is a network-layer control function, but its messages use different transports. OSPF runs directly over IP using protocol number 89; BGP uses TCP port 179; RIP commonly uses UDP port 520. A protocol’s purpose and the encapsulation of its messages are different classification questions. ICMP is carried directly in IP and does not have TCP or UDP ports.'),
('as-and-igp', 'What is an autonomous system, and why use both OSPF and BGP?', 'An autonomous system is a routing domain under a common administrative policy, identified by an AS number. An interior gateway protocol such as OSPF supplies internal reachability; BGP exchanges policy-driven prefix reachability and can distribute it internally using iBGP. An AS may span many locations and networks. It is not the same thing as a subnet or a single router.'),
('ospf-area', 'Does every OSPF router know every link in the entire Internet?', 'No. OSPF’s topology knowledge is scoped to areas and the routing domain. Area border routers connect areas, with area 0 as the backbone in the normal hierarchy. External routes are advertised separately. Dijkstra computes paths from the available topology; it does not discover Internet-wide business policy or guarantee identical tables at every instant during convergence.'),
('bgp-reliability', 'Does BGP using TCP mean the advertised route must be correct?', 'No. Reliable message delivery does not establish authorization to originate a prefix, a safe export policy, or a working data path. Route filters, policy checks, and origin validation address other risks. A route can be syntactically valid and still be a leak or an unwanted path. Control-plane reachability and end-to-end application success require separate verification.'),
('ping-traceroute', 'If ping or traceroute fails, is the destination definitely down?', 'No. ICMP can be filtered or rate-limited while an application still works. Traceroute gradually raises TTL or Hop Limit and observes responses; probes can use UDP, ICMP, or TCP. Asterisks mean no response arrived for that probe, not proof that the hop is absent. Return paths, load balancing, and router response policies can make traces incomplete or asymmetric.'),
('static-default', 'Are static routes and default routes the same?', 'No. Static describes how a route is configured; default describes its prefix length. A static route may target a host, subnet, or default prefix. A default route may also be learned dynamically. The IPv4 default is 0.0.0.0/0; the IPv6 default is ::/0. It applies only when no more-specific route wins under the relevant policy.')
],
6: [
('switch-ip', 'Does a layer-2 switch need an IP address to forward frames?', 'No. Ordinary bridging uses MAC-address learning and destination lookup. A managed switch commonly has an IP address for administration, and a multilayer switch may also have routed interfaces. Those uses are separate from layer-2 forwarding. A device can forward Ethernet frames even when its management IP is misconfigured or unreachable.'),
('router-macs', 'How many MAC addresses does a router have?', 'There is no universal count. Ethernet interfaces normally use MAC addresses, and virtual interfaces or redundancy protocols may add or share them. Some links do not use Ethernet-style MAC addressing. A router’s IP-address count and MAC-address count need not match. Count interfaces and their actual link technologies rather than assuming one hardware identity for the entire router.'),
('arp-remote', 'Do we ARP for a remote server or for the gateway?', 'For an off-link IPv4 destination, resolve the local next-hop gateway’s MAC, not the remote server’s MAC. For an on-link destination, resolve that destination directly. ARP requests stay within the local broadcast domain; ordinary routers do not forward them. Proxy ARP is an explicit exception in which a router answers on another node’s behalf.'),
('mac-changing', 'Does a MAC address change at every switch?', 'In ordinary Ethernet bridging, source and destination MAC addresses stay the same across the switched LAN. A router terminates the incoming link and constructs a new frame for its next link, so link addresses can change at that routing boundary. Tunnels and wireless distribution links have their own encapsulation rules. A MAC address is also not guaranteed to be permanently factory-assigned; software and privacy features can change it.'),
('collision-broadcast', 'What is the difference between a collision domain and a broadcast domain?', 'A collision domain describes competition that can cause collisions on a shared half-duplex medium. A broadcast domain is the scope in which a layer-2 broadcast is delivered. A hub shares collision capacity; a switch separates links. A VLAN defines a separate bridged broadcast domain. Modern full-duplex switched Ethernet has no CSMA/CD collisions on its links, but broadcasts still exist within the VLAN.'),
('link-flow-control', 'Is an Ethernet PAUSE frame the same as TCP flow control?', 'No. IEEE 802.3x PAUSE can ask a directly connected peer to pause data transmission on a full-duplex Ethernet link. It is optional and acts locally. TCP receiver flow control limits one end-to-end byte stream. Pausing a shared link can delay unrelated traffic, so it is not a substitute for end-to-end congestion control. <a href="https://www.cisco.com/c/en/us/td/docs/switches/lan/c9000/lyr2-fwd/flowcontrol-stormcontrol/flow-control-and-storm-control-configuration-guide/configure-flow-control.html">Ethernet flow-control reference</a>.'),
('ethernet-sizes', 'What is the size of an ordinary Ethernet frame?', 'For a conventional untagged Ethernet frame, destination MAC through FCS is 64–1518 bytes: 14 header bytes, 46–1500 payload bytes, and 4 FCS bytes. Padding fills a short payload. The preamble/start delimiter and interframe gap are outside that count. An 802.1Q tag adds 4 bytes to the header. Jumbo-frame support and exact permitted sizes depend on the network.'),
('crc-retransmit', 'Does an Ethernet CRC repair a corrupted frame or request a retry?', 'No. The FCS detects many errors; a corrupted frame is normally discarded. Ordinary Ethernet does not provide per-frame data acknowledgments and retransmissions like Wi-Fi. Recovery may come from a higher layer such as TCP. A checksum, ACK, retransmission timer, and flow-control window are different mechanisms; finding one does not imply that the others are present.'),
('vlan-subnet', 'Are a VLAN and an IP subnet identical?', 'A VLAN partitions a layer-2 network; a subnet is an IP addressing and routing concept. Deployments often map one subnet to one VLAN for clarity, but they are not the same object. Hosts in different VLANs need a layer-3 path to communicate in the usual design. Tags on a trunk identify VLAN membership, not an IP route or encryption boundary.')
],
7: [
('wireless-mobility', 'Are wireless networking and mobility the same?', 'No. A stationary wireless camera uses radio without moving; a laptop can move between wired networks. Wireless describes the medium, while mobility describes a changing attachment point or location. Link association, IP addressing, and application-session continuity are separate states. Good signal strength does not prove that a device has working DNS or Internet access.'),
('ssid-bssid', 'What are SSID, BSSID, and an access point?', 'SSID is the network name visible to users; multiple access points may advertise the same name. A BSSID identifies a basic service set, commonly with a MAC-address-like identifier for an AP radio’s service. An AP can advertise multiple networks. A shared SSID is not proof that two radios are equally trusted, nor does it guarantee seamless roaming.'),
('wifi-ack', 'Does a Wi-Fi ACK mean the web server received the request?', 'No. A Wi-Fi acknowledgment confirms a local link transmission under that protocol’s rules. IP forwarding, transport delivery, and application processing are later stages. A local retransmission may repair radio loss before TCP notices; excessive retries can instead increase RTT and jitter. Broadcast and multicast delivery do not generally use the same individual ACK behavior as ordinary unicast.'),
('hidden-exposed', 'How do hidden and exposed terminals differ?', 'Hidden senders cannot hear one another but can interfere at a common receiver. An exposed sender hears nearby traffic and may defer even when its own transmission could have been safe at another receiver. Carrier sensing alone cannot infer every receiver’s interference conditions. RTS/CTS can reduce hidden-terminal problems but adds overhead and does not eliminate every collision.'),
('wifi-rate', 'Why is Wi-Fi file-transfer speed lower than its displayed link rate?', 'The displayed rate describes a selected physical mode, not exclusive application capacity. Headers, interframe spaces, contention, acknowledgments, retries, and other stations consume airtime. A slow or distant client may occupy substantial airtime even while transferring little data. Wider channels or more antennas do not help if the client, signal conditions, backhaul, or server is the bottleneck.'),
('band-vs-generation', 'Is 5 GHz Wi-Fi the same as 5G cellular?', 'No. 5 GHz is a radio-frequency band used by some Wi-Fi networks. 5G identifies a cellular generation, which can operate in several frequency ranges. Wi-Fi generation names, channel widths, bands, and cellular generations describe different things. Equipment must support the particular band and mode, and local spectrum rules determine what channels may be used.'),
('handover-address', 'Does changing access points always change my IP address?', 'No. Roaming within the same bridged subnet may preserve the address. Moving to another IP subnet can require new addressing unless a mobility mechanism maintains reachability. Cellular networks use session and forwarding state to manage movement. A preserved IP address still does not guarantee uninterrupted application service: authentication, handover delay, packet loss, and timeout settings also matter.'),
('5g-identity', 'Is a SIM identity the same as an IP address?', 'No. Subscriber credentials identify and authenticate a subscription; a packet-data session supplies network connectivity and may assign addresses. Radio identifiers, subscriber identity, phone numbers, and IP addresses have different scopes and lifetimes. In the 5G core, access/mobility management, session management, and user-plane forwarding are separate responsibilities rather than one device doing every task.')
],
8: [
('security-layers', 'At which layer is encryption performed?', 'It depends on the mechanism. Wi-Fi protection acts on the access link; IPsec protects selected IP traffic; TLS protects application channels and is commonly carried over TCP; QUIC integrates TLS-derived security into its transport. Applications can encrypt stored message content as well. State the endpoints and protection boundary rather than assuming “encrypted” means every hop and every stored copy is protected.'),
('https-visibility', 'What can a network observer see when I use HTTPS?', 'Application headers and content are encrypted between the TLS endpoints, but IP addresses, traffic size, and timing usually remain observable. DNS queries and the requested server name may also be visible depending on encrypted DNS and handshake configuration. A CDN or proxy that terminates TLS can read plaintext at that endpoint. HTTPS does not mean that every intermediary operator is excluded from the trust model.'),
('authentication-authorization', 'What is authentication versus authorization?', 'Authentication establishes who or what is making a request. Authorization decides which actions that identity may perform. A valid login does not imply permission to read every record. Encryption protects data in transit or at rest but does not replace either check. Apply authorization at the operation and resource boundary, including requests that come from an internal network.'),
('hash-password', 'Should passwords be encrypted or stored with a fast hash?', 'Authentication services normally store password verifiers using a dedicated password-hashing scheme with a unique salt and a configurable work factor, rather than reversible encryption or a single fast general-purpose hash. A salt prevents identical passwords from producing identical stored values; it is not a secret key. Password handling is distinct from message-integrity hashing and from encryption of data that must later be recovered.'),
('certificate-limits', 'Does a valid certificate prove a website is honest?', 'No. Certificate validation links a public key to an expected identity under a trust policy; the handshake also requires proof of key possession. It does not certify the accuracy of the website’s content or authorize a business transaction. Check the actual hostname and trust chain. A self-signed certificate can encrypt traffic, but clients still need an independent way to trust its key.'),
('tls-forward-secrecy', 'Does every TLS 1.3 connection and every 0-RTT request have forward secrecy?', 'No. Ephemeral (EC)DHE key agreement provides forward secrecy for the resulting traffic. TLS 1.3 also defines PSK-only key exchange, which does not provide the same guarantee; early 0-RTT data has no full forward secrecy and can be replayed. The ordinary certificate-and-(EC)DHE handshake taught here is one important mode, not every permitted handshake. <a href="https://www.rfc-editor.org/rfc/rfc8446.html#section-2.3">TLS 1.3 early-data limits</a>.'),
('vpn-limits', 'Does a VPN make traffic anonymous or safe after it leaves the tunnel?', 'A VPN protects a defined tunnel between endpoints. Traffic leaving a VPN gateway depends on its remaining protections, such as HTTPS. The gateway operator becomes part of the trust model; destinations can still identify users through accounts or application state. Tunnel encryption does not repair an infected endpoint, eliminate tracking, or prove that the destination is trustworthy.'),
('replay-and-nonce', 'Why are nonces, salts, and initialization vectors different?', 'A nonce supplies uniqueness or freshness in a protocol; an initialization vector is an algorithm input whose requirements depend on the encryption mode; a salt randomizes a password or key-derivation input. They are not interchangeable. Some modes require unpredictability, others uniqueness. A fresh number only helps if the protocol authenticates its relationship to the message, identities, and current session.')
]
}

REFERENCES = {
1: [('Internet host requirements and layering', 'https://www.rfc-editor.org/rfc/rfc1122.html'), ('IPv4 router requirements', 'https://www.rfc-editor.org/rfc/rfc1812.html')],
2: [('HTTP semantics — RFC 9110', 'https://www.rfc-editor.org/rfc/rfc9110.html'), ('DNS concepts — RFC 1034', 'https://www.rfc-editor.org/rfc/rfc1034.html'), ('QUIC transport — RFC 9000', 'https://www.rfc-editor.org/rfc/rfc9000.html'), ('Python socket programming', 'https://docs.python.org/3/howto/sockets.html'), ('IANA service names and transport ports', 'https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml')],
3: [('TCP retransmission timer — RFC 6298', 'https://www.rfc-editor.org/rfc/rfc6298.html'), ('TCP — RFC 9293', 'https://www.rfc-editor.org/rfc/rfc9293.html'), ('TCP congestion control — RFC 5681', 'https://www.rfc-editor.org/rfc/rfc5681.html'), ('QUIC loss detection and congestion control — RFC 9002', 'https://www.rfc-editor.org/rfc/rfc9002.html')],
4: [('IPv6 addressing — RFC 4291', 'https://www.rfc-editor.org/rfc/rfc4291.html'), ('IPv6 protocol — RFC 8200', 'https://www.rfc-editor.org/rfc/rfc8200.html'), ('IPv4 /31 links — RFC 3021', 'https://www.rfc-editor.org/rfc/rfc3021.html'), ('DHCP — RFC 2131', 'https://www.rfc-editor.org/rfc/rfc2131.html'), ('Private IPv4 space — RFC 1918', 'https://www.rfc-editor.org/rfc/rfc1918.html')],
5: [('OSPFv2 — RFC 2328', 'https://www.rfc-editor.org/rfc/rfc2328.html'), ('BGP-4 — RFC 4271', 'https://www.rfc-editor.org/rfc/rfc4271.html')],
6: [('ARP — RFC 826', 'https://www.rfc-editor.org/rfc/rfc826.html'), ('Ethernet flow control — Cisco', 'https://www.cisco.com/c/en/us/td/docs/switches/lan/c9000/lyr2-fwd/flowcontrol-stormcontrol/flow-control-and-storm-control-configuration-guide/configure-flow-control.html')],
7: [('IEEE 802.11 wireless LAN standards', 'https://www.ieee802.org/11/'), ('5G system architecture — 3GPP TS 23.501, Release 16 (PDF)', 'https://www.etsi.org/deliver/etsi_ts/123500_123599/123501/16.06.00_60/ts_123501v160600p.pdf')],
8: [('TLS 1.3 — RFC 8446', 'https://www.rfc-editor.org/rfc/rfc8446.html'), ('IPsec architecture — RFC 4301', 'https://www.rfc-editor.org/rfc/rfc4301.html'), ('Password storage — OWASP', 'https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html')]
}
