"""Layer-by-layer explanations of sizes, mechanisms, and their limits.

Each chapter entry has a title, cards, a worked example, and primary sources.
"""
LAYER_DETAILS = {
1: {
 'title': 'Physical layer: signals, rates, and delay',
 'cards': [
 ('Why bits per second and baud are different', 'Baud counts symbols per second; bit rate counts bits. With M distinct symbols, an ideal symbol can represent log₂(M) bits. Four symbols encode two bits each, so 1 million symbols/s carries 2 Mb/s before coding overhead. Error-correcting codes, pilots, guard intervals, and framing reduce the useful data rate. More symbols require the receiver to distinguish more closely spaced signal states.'),
 ('Why bandwidth does not remove propagation delay', 'Transmission delay is L/R: packet bits divided by link bit rate. Propagation delay is distance/signal speed. Increasing R shortens serialization, but does not make the signal travel faster. Queueing and processing add separate delays. A repeater regenerates signals; it does not select an IP route.'),
 ('Why there is no universal physical-layer header size', 'The physical layer encodes link frames into electrical, optical, or radio signals. Synchronization, training, modulation, and forward error correction depend on the particular PHY. An Ethernet preamble is not an IP header, and a Wi-Fi PHY preamble is not the 802.11 MAC header. Always state the technology before assigning an overhead size.'),
 ('Where session and presentation fit', 'The seven-layer OSI model separates application, presentation, and session functions. The Internet stack normally implements these in application protocols and libraries: encoding/compression, cryptographic protection, dialog state, and resumption. They have no universal mandatory session or presentation header. TLS records and application cookies are concrete mechanisms, not fixed headers that every packet must contain.')],
 'example': ('Separate two kinds of delay', 'A 1500-byte packet takes 1500 × 8 / 100,000,000 = 120 μs to serialize at 100 Mb/s. A 1000 km fiber path at an assumed 2 × 10⁸ m/s adds 5 ms one-way propagation. This simplified total is 5.12 ms before queueing, processing, and link overhead.'),
 'sources': [('Internet host layering — RFC 1122','https://www.rfc-editor.org/rfc/rfc1122.html')]
},
2: {
 'title': 'Application layer: message sizes and boundaries',
 'cards': [
 ('Why DNS has a 12-byte header', 'The base DNS header has six 16-bit fields: transaction ID, flags, and four counts for questions, answers, authority records, and additional records. That is 6 × 2 = 12 bytes before any names or records. Flags distinguish query/response, truncation, recursion, and response status; counts describe entries, not byte lengths.'),
 ('Why DNS is not limited to 512 bytes today', 'Classic DNS over UDP used a 512-byte message limit, excluding UDP/IP headers. EDNS lets a requester advertise a larger UDP payload size; it does not guarantee that the path can carry it without fragmentation. A truncated response can trigger TCP retry. DNS over TCP prefixes each message with a two-byte length so a receiver can separate messages in the byte stream. A standard DNS label is at most 63 octets; a complete encoded name is at most 255 octets including length fields and the root terminator.'),
 ('Why HTTP headers have no single fixed size', 'HTTP/1.1 uses a start line, variable field lines, a blank line, and an optional body. Content-Length counts body octets, not characters or the entire message. Chunked framing is a different way to delimit a body. HTTP/2 and HTTP/3 use binary framing and compressed field sections, so HTTP/1.1 wire-layout rules cannot simply be copied to them. Servers impose implementation-specific header limits.'),
 ('Why application messages can exceed MSS', 'TCP can split one application message across many segments or combine bytes from multiple writes. An application needs framing, such as a length prefix, delimiter, or protocol-defined structure. A TCP ACK acknowledges received bytes; an HTTP status or application receipt communicates a different result. Neither DNS TTL nor an HTTP cache lifetime is an IP hop limit.')],
 'example': ('Count a simple DNS query', 'For one uncompressed A query for example.com with no EDNS or other records: the name takes 1+7+1+3+1 = 13 bytes. Add QTYPE 2 and QCLASS 2, then the 12-byte header: 29 bytes of DNS. UDP adds 8 and minimum IPv4 adds 20, producing a 57-byte IP packet.'),
 'sources': [('DNS wire format — RFC 1035','https://www.rfc-editor.org/rfc/rfc1035.html'),('EDNS — RFC 6891','https://www.rfc-editor.org/rfc/rfc6891.html'),('HTTP/1.1 framing — RFC 9112','https://www.rfc-editor.org/rfc/rfc9112.html')]
},
3: {
 'title': 'Transport layer: header fields, windows, and checksums',
 'cards': [
 ('Why UDP has an 8-byte header', 'Source port, destination port, length, and checksum each occupy 16 bits: 4 × 2 = 8 bytes. Length includes the UDP header and data. The ordinary 16-bit field can encode at most 65,535 bytes, but IPv4’s total-length limit leaves at most 65,507 UDP payload bytes with a 20-byte IP header. That theoretical size usually requires fragmentation; at MTU 1500, the corresponding unfragmented payload limit is 1472.'),
 ('Why TCP headers range from 20 to 60 bytes', 'The fixed fields occupy 20 bytes. The four-bit Data Offset counts 32-bit words, so its maximum value 15 describes 60 header bytes; options and padding have at most 40 bytes. Options carry capabilities such as MSS, window scaling, timestamps, and SACK. The 1460-byte result assumes minimum headers; follow the MTU/header lesson in Chapter 4 for the complete byte budget.'),
 ('Why TCP window scaling exists', 'The base receive-window field is 16 bits: at most 65,535 bytes. That can be too small on a high-rate, long-RTT path. The Window Scale option negotiates a shift during connection setup; the window in SYN-bearing segments is not scaled. The receive window controls receiver capacity, whereas the sender’s congestion window controls network pressure. Neither is a segment-size limit.'),
 ('Why a pseudo-header is not extra transmitted overhead', 'TCP and UDP checksums include selected IP information, the transport header, and data. The pseudo-header is constructed for checksum computation; it is not appended as another header on the wire. IPv4 UDP can omit its checksum using a zero field, while ordinary IPv6 UDP requires it. TCP requires a checksum. These checks detect accidental corruption, not a malicious sender.')],
 'example': ('A window can limit a fast connection', 'Ignoring loss and overhead, a 65,535-byte window over a 100 ms RTT gives 65,535 × 8 / 0.1 = 5.24 Mb/s. A 100 Mb/s path needs about 1,250,000 bytes in flight at that RTT. Window scaling helps represent a larger receive window, but it does not override congestion control or create capacity.'),
 'sources': [('UDP — RFC 768','https://www.rfc-editor.org/rfc/rfc768.html'),('TCP — RFC 9293','https://www.rfc-editor.org/rfc/rfc9293.html'),('Window scaling — RFC 7323','https://www.rfc-editor.org/rfc/rfc7323.html')]
},
4: {
 'title': 'Network layer: length fields, hops, and fragments',
 'cards': [
 ('Why IPv4 packets have a 65,535-byte ceiling', 'IPv4 Total Length is 16 bits and counts the whole IP packet, including its header. Therefore the largest representable packet is 65,535 bytes. IHL instead counts 32-bit header words: IHL 5 means 20 bytes, IHL 15 means 60. Neither number overrides a link’s smaller MTU. IPv4 addresses are 32 bits; address width and packet-length width are independent choices.'),
 ('Why IPv6’s length field counts different bytes', 'IPv6 has a fixed 40-byte base header. Its 16-bit Payload Length normally counts everything after that header, including extension headers. A normal payload can be 65,535 bytes, for 65,575 bytes including the base header. Special jumbograms use different rules. IPv6 requires a link MTU of at least 1280 bytes; a link unable to carry that directly must adapt below IPv6. This is a minimum capability, not the MTU of every IPv6 link.'),
 ('Why TTL changes but MAC addresses are replaced', 'A router decrements IPv4 TTL or IPv6 Hop Limit when forwarding. These eight-bit fields bound forwarding loops; they are not an elapsed-time stopwatch in normal operation. For IPv4 the header checksum must be updated. The router removes the incoming link encapsulation and creates one for the outgoing link. End-to-end IP addresses normally remain, unless NAT or another transformation applies.'),
 ('Why fragment offsets count groups of eight bytes', 'IPv4 has a 13-bit fragment-offset field measured in eight-byte units, allowing it to describe positions across the packet’s length range. Each nonfinal fragment’s data length must be a multiple of eight. Offsets refer to the original IP payload, not the fragment header. Reassembly is at the destination; IPv6 routers do not fragment transit packets.')],
 'example': ('Fragment a 4000-byte IPv4 packet at MTU 1500', 'Assume a 20-byte header with no options and fragmentation permitted. Original payload = 3980 bytes. Fragment payloads are 1480, 1480, and 1020; total fragment lengths are 1500, 1500, and 1040. Offsets are 0, 185, and 370 because 1480/8 = 185. More Fragments is 1, 1, then 0. Only the first fragment starts with the original transport header.'),
 'sources': [('IPv4 format — RFC 791','https://www.rfc-editor.org/rfc/rfc791.html'),('IPv6 format and MTU — RFC 8200','https://www.rfc-editor.org/rfc/rfc8200.html')]
},
5: {
 'title': 'Control plane: protocol numbers and route decisions',
 'cards': [
 ('Why ICMP has no TCP or UDP port', 'ICMP is carried directly in IP: IPv4 Protocol 1 or IPv6 Next Header 58. Its common opening fields are Type (1 byte), Code (1), and Checksum (2); the remainder depends on the message. An Echo header adds a two-byte identifier and two-byte sequence number, making 8 bytes before echo data. Do not label every ICMP message as only an eight-byte packet.'),
 ('Why OSPF is not a TCP service', 'OSPFv2 is carried directly in IPv4 with Protocol 89. Its common packet header is 24 bytes: version, type, length, router ID, area ID, checksum, authentication type, and authentication data. Hellos discover and maintain neighbors; link-state updates advertise topology. OSPFv3 has a different format, so the v2 header size is not universal.'),
 ('Why BGP has its own header above TCP', 'BGP uses TCP port 179, but still needs application message boundaries. Its common header is 19 bytes: a 16-byte marker, two-byte length, and one-byte type. TCP reliability moves bytes; BGP policy decides which routes to accept, prefer, and advertise. A valid BGP session does not prove that a selected route works or that an origin is authorized.'),
 ('Why longest-prefix match comes before route preference', 'Forwarding selects the most specific matching installed prefix. Route-source preferences and protocol metrics help choose candidate routes for a prefix; they do not make a default route beat an installed /24 for the same destination. Metrics from different routing protocols are not automatically comparable. Control-plane selection and per-packet forwarding are distinct steps.')],
 'example': ('Choose the route for 10.1.2.9', 'Installed routes 0.0.0.0/0, 10.0.0.0/8, and 10.1.2.0/24 all match. The /24 wins because it fixes the most destination bits, even if the default route came from a supposedly preferred source. If the /24 disappears, the /8 can become the best remaining match.'),
 'sources': [('ICMP — RFC 792','https://www.rfc-editor.org/rfc/rfc792.html'),('OSPFv2 — RFC 2328','https://www.rfc-editor.org/rfc/rfc2328.html'),('BGP — RFC 4271','https://www.rfc-editor.org/rfc/rfc4271.html'),('CIDR forwarding — RFC 4632','https://www.rfc-editor.org/rfc/rfc4632.html')]
},
6: {
 'title': 'Data-link layer: minimum frames, MACs, and local scope',
 'cards': [
 ('Why Ethernet has a 64-byte minimum frame', 'For ordinary untagged Ethernet, 14 header bytes + at least 46 payload/padding bytes + 4 FCS bytes = 64. The historical minimum let a sender remain transmitting long enough to detect a collision on a correctly bounded shared Ethernet. At 10 Mb/s, 512 bit-times equals 51.2 μs. Modern full-duplex Ethernet does not use CSMA/CD, but retains the minimum frame format.'),
 ('Why a short IP packet needs padding', 'Ethernet padding meets the link minimum and is not part of IP Total Length. A 40-byte IPv4/TCP ACK with no options needs six padding bytes in an untagged Ethernet frame. Preamble/start delimiter add eight bytes outside the frame count; the interframe gap is idle time equivalent to twelve bytes. A capture may omit FCS and physical overhead, so captured length and wire occupancy can differ.'),
 ('Why ARP has no port number', 'ARP is carried directly by Ethernet using EtherType 0x0806; it is not an IP, TCP, or UDP payload. For Ethernet/IPv4, its message is 28 bytes: hardware/protocol types, address lengths, operation, and sender/target MAC and IP addresses. A request usually broadcasts locally; the reply is usually unicast. Routers do not forward that Ethernet broadcast to every remote subnet.'),
 ('Why switches learn the source but forward by destination', 'A bridge learns which ingress port reaches a source MAC, then consults the destination MAC to forward. Unknown unicast and broadcast are normally flooded only within the VLAN, subject to policy. A MAC address is commonly 48 bits, but it is not proof of identity or permanently tied to hardware. Locally administered and randomized addresses exist. A VLAN tag has a 12-bit VLAN ID; 0 and 4095 are reserved, leaving 1–4094 for ordinary VLAN IDs.')],
 'example': ('The packet rate cost of tiny frames', 'At a 1 Gb/s Ethernet MAC rate, a stream of minimum frames occupies 64 + 8 + 12 = 84 byte-times each. The ideal maximum is 1,000,000,000 / (84 × 8) ≈ 1.488 million frames/s. This assumes ordinary framing and continuous transmission; it is a frame-rate calculation, not application goodput.'),
 'sources': [('Ethernet timing and padding — Cisco','https://www.cisco.com/en/US/docs/internetworking/troubleshooting/guide/tr1904.html'),('ARP — RFC 826','https://www.rfc-editor.org/rfc/rfc826.html'),('IP over Ethernet — RFC 894','https://www.rfc-editor.org/rfc/rfc894.html')]
},
7: {
 'title': 'Wireless layers: airtime, addresses, and acknowledgments',
 'cards': [
 ('Why Wi-Fi needs more than Ethernet’s two MAC addresses', 'A wireless hop may involve a station, an access point, and a different original source or final destination in the distribution system. A basic three-address 802.11 data header is 24 bytes: Frame Control 2, Duration/ID 2, three addresses of 6 each, and Sequence Control 2. Four-address, QoS, and other variants add fields; control frames can be shorter. There is no single header size for every Wi-Fi frame.'),
 ('Why Wi-Fi uses collision avoidance', 'A radio’s own transmission can overwhelm a weak incoming signal, so collision detection while transmitting is not like shared wired Ethernet. Stations sense the medium and contend with backoff; many unicast frames use link acknowledgments and retries. Hidden stations can collide at a receiver even when each hears an idle channel. RTS/CTS can reserve airtime in suitable cases but adds overhead and does not eliminate all interference.'),
 ('Why the advertised Wi-Fi rate is not download speed', 'The PHY rate describes a selected signaling mode, not useful application throughput. Preambles, MAC headers, security overhead, interframe spacing, contention, acknowledgments, and retries consume airtime. Channel width, modulation/coding, spatial streams, and signal conditions affect the rate. Aggregation amortizes overhead; slow or repeatedly retried transmissions occupy airtime that others cannot use simultaneously.'),
 ('Why a Wi-Fi ACK is not a TCP ACK', 'A Wi-Fi acknowledgment confirms a local wireless reception under that link protocol; a TCP ACK concerns end-to-end byte receipt. Local retries can hide some radio loss from TCP, while also increasing delay. Neither acknowledgment establishes that a server committed an application transaction. Roaming between access points and changing an IP subnet are also different events.')],
 'example': ('A payload-only airtime lower bound', 'Sending 1500 bytes at a constant 54 Mb/s takes 1500 × 8 / 54,000,000 ≈ 222 μs for those bits alone. Real airtime is longer because PHY framing, MAC overhead, contention, and feedback must be included. Do not compute a reliable download rate by treating 54 Mb/s as pure application data.'),
 'sources': [('IEEE 802.11 standards','https://www.ieee802.org/11/'),('Cisco wireless protocol guide','https://www.cisco.com/c/en/us/td/docs/wireless/controller/8-10/config-guide/b_cg810.pdf')]
},
8: {
 'title': 'Presentation and session functions: TLS records and state',
 'cards': [
 ('Why TLS adds another framing layer', 'TLS over TCP groups protected content into records. A TLS 1.3 encrypted record has a five-byte outer header: content type (1), legacy record version (2), and length (2). Its ciphertext contains content, an inner content-type byte, optional padding, and an authentication tag. Tag size depends on the cipher suite. TLS records and TCP segments need not align.'),
 ('Why encryption reduces useful payload', 'With TLS_AES_128_GCM_SHA256 and no padding, a TLS 1.3 record carrying 1000 application bytes adds 5 header + 1 inner type + 16 tag = 22 bytes, giving 1022 TCP-stream bytes. Other suites or padding change the overhead. Handshake and certificate traffic are separate. Compression, encoding, and encryption are different transformations; base64 is encoding, not encryption.'),
 ('Why a checksum does not replace authentication', 'Ethernet CRC and ordinary IP/transport checksums detect accidental errors; an attacker can recompute them. Authenticated encryption checks protected content and associated metadata using secret-key material. Certificate validation binds the handshake to an expected service identity under a trust policy. Encryption alone does not prove that the peer is the intended server.'),
 ('Why resuming a session is not a login guarantee', 'TLS session resumption can reduce handshake work, but the application still manages authorization, cookies, expiration, and logout. TLS 1.3 early data can be replayed, so applications must restrict or protect operations whose repetition matters. Transport reconnection, TLS resumption, and an application session are three different states; none supplies a universal OSI session-header size.')],
 'example': ('One application record can span many TCP segments', 'A TLS 1.3 record with 16,384 application bytes, one inner type byte, a 16-byte GCM tag, no padding, and the five-byte outer header uses 16,406 TCP-stream bytes. At an assumed 1460-byte TCP data budget it needs at least ceil(16,406/1460) = 12 segments. Options, lower path MTU, or implementation buffering can change the actual segmentation.'),
 'sources': [('TLS 1.3 record layer and replay limits — RFC 8446','https://www.rfc-editor.org/rfc/rfc8446.html')]
}

}
